
apiVersion: v1
kind: Namespace
metadata:
  name: ns-demo-anish-sahariar

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: ns-demo-anish-sahariar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: 840249918025.dkr.ecr.us-east-2.amazonaws.com/demo:idwttrdowb
          ports:
            - containerPort: 80
